# Generated by Django 5.1 on 2024-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_alter_contact_description_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
