# Generated by Django 5.2.5 on 2025-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, null=True, to='blogpost.c_like'),
        ),
    ]
